#!/bin/sh

ipp (){

exec < $1
while read a
do
sring=`curl -s  "http://ip138.com/ips138.asp?ip=${a}&action=2" |grep '<ul class="ul1"><li>' |awk -F'[><]+' '{
print $5}'`
echo $a $sring
done
}
case $1 in
-f)
        shift
        ipp $1
;;
-i)
        shift
        
     if [ $# -ge 1 ]; then
     {
       #echo -e 'start query .....'
        sring=`curl -s  "http://ip138.com/ips138.asp?ip=${1}&action=2" |grep '<ul class="ul1"><li>' |awk -F'[><]+' '{print $5}'`
      echo $1 $sring
     }
     else
     {
        ipdt=`curl -s icanhazip.com`
        #echo $ipdt
        sring=`curl -s  "http://ip138.com/ips138.asp?ip=${ipdt}&action=2" |grep '<ul class="ul1"><li>' |awk -F'[><]+' '{print $5}'`
        echo 国外:$ipdt $sring
        echo 国内:`curl -s ip138.com/ips138.asp | grep '<td align="center">您' |awk -F'[><]+' '{print $3}''`
     }
     fi

       
     
;;
*)
        echo "[Help]
        $0 need -f or -i
        -f ------- argument is a file
        -i ------- argument is a IP
[For example]:
        $0 -f filename
        $0 -i ipadress
        "
;;
esac
